spring:
  application:
    name: auth-flyway
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/changeme}
    username: ${AUTH_DB_USER:changeme}
    password: ${AUTH_DB_PWD:changeme}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: ${AUTH_DB_SCHEMA:changeme}
    default-schema: ${AUTH_DB_SCHEMA:changeme}
    create-schemas: true

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:flyway;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: auth_schema
    default-schema: auth_schema
    create-schemas: true


