spring:
  application:
    name: auth-flyway
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${DB_USERNAME:pguser}
    password: ${DB_PASSWORD:start123}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: ${DB_SCHEMA:auth_schema}
    default-schema: ${DB_SCHEMA:auth_schema}
    create-schemas: true

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:flyway;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: auth_schema
    default-schema: auth_schema
    create-schemas: true


