spring:
  application:
    name: auth-server

  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PWD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: ${AUTH_DB_SCHEMA}
    show-sql: false
    properties:
      hibernate:
        default_schema: ${AUTH_DB_SCHEMA}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      authorization-server:
        client:
          postgres:
            registration:
              client-id: postgres
              client-secret: postgres-secret
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://localhost:3000/callback
              scopes:
                - openid
                - profile
                - email
                - read
                - write

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.auth: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  jwt:
    access-token-validity: 3600 # 1 hour
    refresh-token-validity: 86400 # 24 hours
    rsa:
      private-key-path: classpath:keys/private.pem
      public-key-path: classpath:keys/public.pem

  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:3001
      - https://yourdomain.com
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    allow-credentials: true
    max-age: 3600

  email:
    verification:
      enabled: true
      expiration-hours: 24
      from: noreply@authserver.com
      subject: "Verify Your Email Address"

  mfa:
    enabled: true
    issuer: "Auth Server"
    algorithm: "SHA1"
    digits: 6
    period: 30

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 25
